#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Include server_spec.yml
  block:
    - name: Include server_spec file
      ansible.builtin.include_vars: "{{ server_spec }}"
      register: include_server_spec
      no_log: true
      tags: init
  rescue:
    - name: Failed to include server_spec.yml
      ansible.builtin.fail:
        msg: "{{ server_spec_syntax_fail_msg }} Error: {{ include_server_spec.message }}"

- name: Parse server_spec data for categories
  ansible.builtin.set_fact:
    category_list: "{{ category_list | default([]) + [item.key] }}"
  with_dict: "{{ Categories }}"

- name: Validate inventory file
  block:
    - name: Validate the inventory file
      ansible.builtin.command: |
        {{ python_version }} {{ validate_inventory_py }}
      register: script_output
      changed_when: false
      environment:
        host_data: "{{ hostvars | to_json }}"
        category_list: "{{ category_list }}"
  rescue:
    - name: Failed to validate inventory file
      ansible.builtin.fail:
        msg: "{{ inventory_fail_msg }} Error: {{ script_output.stderr }}"
